#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOMTSU
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KOMTSU")]
	public partial class DataKomtsuDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Batch(tbl_Batch instance);
    partial void Updatetbl_Batch(tbl_Batch instance);
    partial void Deletetbl_Batch(tbl_Batch instance);
    partial void Inserttbl_MissImage_DESO(tbl_MissImage_DESO instance);
    partial void Updatetbl_MissImage_DESO(tbl_MissImage_DESO instance);
    partial void Deletetbl_MissImage_DESO(tbl_MissImage_DESO instance);
    partial void Inserttbl_DEJP(tbl_DEJP instance);
    partial void Updatetbl_DEJP(tbl_DEJP instance);
    partial void Deletetbl_DEJP(tbl_DEJP instance);
    partial void Inserttbl_DEJP_Backup(tbl_DEJP_Backup instance);
    partial void Updatetbl_DEJP_Backup(tbl_DEJP_Backup instance);
    partial void Deletetbl_DEJP_Backup(tbl_DEJP_Backup instance);
    partial void Inserttbl_DESO(tbl_DESO instance);
    partial void Updatetbl_DESO(tbl_DESO instance);
    partial void Deletetbl_DESO(tbl_DESO instance);
    partial void Inserttbl_DESO_Backup(tbl_DESO_Backup instance);
    partial void Updatetbl_DESO_Backup(tbl_DESO_Backup instance);
    partial void Deletetbl_DESO_Backup(tbl_DESO_Backup instance);
    partial void Inserttbl_Image(tbl_Image instance);
    partial void Updatetbl_Image(tbl_Image instance);
    partial void Deletetbl_Image(tbl_Image instance);
    partial void Inserttbl_LogFile(tbl_LogFile instance);
    partial void Updatetbl_LogFile(tbl_LogFile instance);
    partial void Deletetbl_LogFile(tbl_LogFile instance);
    partial void Inserttbl_MissCheck_DEJP(tbl_MissCheck_DEJP instance);
    partial void Updatetbl_MissCheck_DEJP(tbl_MissCheck_DEJP instance);
    partial void Deletetbl_MissCheck_DEJP(tbl_MissCheck_DEJP instance);
    partial void Inserttbl_MissCheck_DESO(tbl_MissCheck_DESO instance);
    partial void Updatetbl_MissCheck_DESO(tbl_MissCheck_DESO instance);
    partial void Deletetbl_MissCheck_DESO(tbl_MissCheck_DESO instance);
    partial void Inserttbl_MissImage_DEJP(tbl_MissImage_DEJP instance);
    partial void Updatetbl_MissImage_DEJP(tbl_MissImage_DEJP instance);
    partial void Deletetbl_MissImage_DEJP(tbl_MissImage_DEJP instance);
    #endregion
		
		public DataKomtsuDataContext() : 
				base(global::KOMTSU.Properties.Settings.Default.KOMTSUConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataKomtsuDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataKomtsuDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataKomtsuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataKomtsuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Batch> tbl_Batches
		{
			get
			{
				return this.GetTable<tbl_Batch>();
			}
		}
		
		public System.Data.Linq.Table<tbl_MissImage_DESO> tbl_MissImage_DESOs
		{
			get
			{
				return this.GetTable<tbl_MissImage_DESO>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DataAutoComplete> tbl_DataAutoCompletes
		{
			get
			{
				return this.GetTable<tbl_DataAutoComplete>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DEJP> tbl_DEJPs
		{
			get
			{
				return this.GetTable<tbl_DEJP>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DEJP_Backup> tbl_DEJP_Backups
		{
			get
			{
				return this.GetTable<tbl_DEJP_Backup>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DESO> tbl_DESOs
		{
			get
			{
				return this.GetTable<tbl_DESO>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DESO_Backup> tbl_DESO_Backups
		{
			get
			{
				return this.GetTable<tbl_DESO_Backup>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Image> tbl_Images
		{
			get
			{
				return this.GetTable<tbl_Image>();
			}
		}
		
		public System.Data.Linq.Table<tbl_LogFile> tbl_LogFiles
		{
			get
			{
				return this.GetTable<tbl_LogFile>();
			}
		}
		
		public System.Data.Linq.Table<tbl_MissCheck_DEJP> tbl_MissCheck_DEJPs
		{
			get
			{
				return this.GetTable<tbl_MissCheck_DEJP>();
			}
		}
		
		public System.Data.Linq.Table<tbl_MissCheck_DESO> tbl_MissCheck_DESOs
		{
			get
			{
				return this.GetTable<tbl_MissCheck_DESO>();
			}
		}
		
		public System.Data.Linq.Table<tbl_MissImage_DEJP> tbl_MissImage_DEJPs
		{
			get
			{
				return this.GetTable<tbl_MissImage_DEJP>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LayHinhMoi_DeJP")]
		public ISingleResult<LayHinhMoi_DeJPResult> LayHinhMoi_DeJP([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string fbatchname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fbatchname, username);
			return ((ISingleResult<LayHinhMoi_DeJPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insert_Loai1")]
		public int Insert_Loai1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdImage", DbType="NVarChar(255)")] string idImage, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string fBatchName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(255)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_03", DbType="NVarChar(255)")] string truong_03, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_04", DbType="NVarChar(255)")] string truong_04, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_05", DbType="NVarChar(255)")] string truong_05, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_07", DbType="NVarChar(255)")] string truong_07, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_09", DbType="NVarChar(255)")] string truong_09, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_10", DbType="NVarChar(255)")] string truong_10, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_11", DbType="NVarChar(255)")] string truong_11, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_12", DbType="NVarChar(255)")] string truong_12, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoaiPhieu", DbType="NVarChar(255)")] string loaiPhieu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idImage, fBatchName, userName, truong_03, truong_04, truong_05, truong_07, truong_09, truong_10, truong_11, truong_12, loaiPhieu);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Batch")]
	public partial class tbl_Batch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDBatch;
		
		private string _fBatchName;
		
		private System.Nullable<System.DateTime> _fdatecreated;
		
		private string _fusercreate;
		
		private string _fPathPicture;
		
		private string _fLocation;
		
		private string _fSoLuongAnh;
		
		private string _TruongSo06;
		
		private string _TruongSo08;
		
		private string _LoaiBatch;
		
		private System.Nullable<bool> _CoDeSo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBatchChanging(int value);
    partial void OnIDBatchChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnfdatecreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnfdatecreatedChanged();
    partial void OnfusercreateChanging(string value);
    partial void OnfusercreateChanged();
    partial void OnfPathPictureChanging(string value);
    partial void OnfPathPictureChanged();
    partial void OnfLocationChanging(string value);
    partial void OnfLocationChanged();
    partial void OnfSoLuongAnhChanging(string value);
    partial void OnfSoLuongAnhChanged();
    partial void OnTruongSo06Changing(string value);
    partial void OnTruongSo06Changed();
    partial void OnTruongSo08Changing(string value);
    partial void OnTruongSo08Changed();
    partial void OnLoaiBatchChanging(string value);
    partial void OnLoaiBatchChanged();
    partial void OnCoDeSoChanging(System.Nullable<bool> value);
    partial void OnCoDeSoChanged();
    #endregion
		
		public tbl_Batch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBatch", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IDBatch
		{
			get
			{
				return this._IDBatch;
			}
			set
			{
				if ((this._IDBatch != value))
				{
					this.OnIDBatchChanging(value);
					this.SendPropertyChanging();
					this._IDBatch = value;
					this.SendPropertyChanged("IDBatch");
					this.OnIDBatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fdatecreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> fdatecreated
		{
			get
			{
				return this._fdatecreated;
			}
			set
			{
				if ((this._fdatecreated != value))
				{
					this.OnfdatecreatedChanging(value);
					this.SendPropertyChanging();
					this._fdatecreated = value;
					this.SendPropertyChanged("fdatecreated");
					this.OnfdatecreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fusercreate", DbType="NVarChar(200)")]
		public string fusercreate
		{
			get
			{
				return this._fusercreate;
			}
			set
			{
				if ((this._fusercreate != value))
				{
					this.OnfusercreateChanging(value);
					this.SendPropertyChanging();
					this._fusercreate = value;
					this.SendPropertyChanged("fusercreate");
					this.OnfusercreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPathPicture", DbType="NVarChar(200)")]
		public string fPathPicture
		{
			get
			{
				return this._fPathPicture;
			}
			set
			{
				if ((this._fPathPicture != value))
				{
					this.OnfPathPictureChanging(value);
					this.SendPropertyChanging();
					this._fPathPicture = value;
					this.SendPropertyChanged("fPathPicture");
					this.OnfPathPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fLocation", DbType="NVarChar(200)")]
		public string fLocation
		{
			get
			{
				return this._fLocation;
			}
			set
			{
				if ((this._fLocation != value))
				{
					this.OnfLocationChanging(value);
					this.SendPropertyChanging();
					this._fLocation = value;
					this.SendPropertyChanged("fLocation");
					this.OnfLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fSoLuongAnh", DbType="NVarChar(200)")]
		public string fSoLuongAnh
		{
			get
			{
				return this._fSoLuongAnh;
			}
			set
			{
				if ((this._fSoLuongAnh != value))
				{
					this.OnfSoLuongAnhChanging(value);
					this.SendPropertyChanging();
					this._fSoLuongAnh = value;
					this.SendPropertyChanged("fSoLuongAnh");
					this.OnfSoLuongAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo06", DbType="NVarChar(200)")]
		public string TruongSo06
		{
			get
			{
				return this._TruongSo06;
			}
			set
			{
				if ((this._TruongSo06 != value))
				{
					this.OnTruongSo06Changing(value);
					this.SendPropertyChanging();
					this._TruongSo06 = value;
					this.SendPropertyChanged("TruongSo06");
					this.OnTruongSo06Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo08", DbType="NVarChar(200)")]
		public string TruongSo08
		{
			get
			{
				return this._TruongSo08;
			}
			set
			{
				if ((this._TruongSo08 != value))
				{
					this.OnTruongSo08Changing(value);
					this.SendPropertyChanging();
					this._TruongSo08 = value;
					this.SendPropertyChanged("TruongSo08");
					this.OnTruongSo08Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiBatch", DbType="NVarChar(200)")]
		public string LoaiBatch
		{
			get
			{
				return this._LoaiBatch;
			}
			set
			{
				if ((this._LoaiBatch != value))
				{
					this.OnLoaiBatchChanging(value);
					this.SendPropertyChanging();
					this._LoaiBatch = value;
					this.SendPropertyChanged("LoaiBatch");
					this.OnLoaiBatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoDeSo", DbType="Bit")]
		public System.Nullable<bool> CoDeSo
		{
			get
			{
				return this._CoDeSo;
			}
			set
			{
				if ((this._CoDeSo != value))
				{
					this.OnCoDeSoChanging(value);
					this.SendPropertyChanging();
					this._CoDeSo = value;
					this.SendPropertyChanged("CoDeSo");
					this.OnCoDeSoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_MissImage_DESO")]
	public partial class tbl_MissImage_DESO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private System.Nullable<int> _Submit;
		
		private System.Nullable<System.DateTime> _DateInput;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnSubmitChanging(System.Nullable<int> value);
    partial void OnSubmitChanged();
    partial void OnDateInputChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInputChanged();
    #endregion
		
		public tbl_MissImage_DESO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Submit", DbType="Int")]
		public System.Nullable<int> Submit
		{
			get
			{
				return this._Submit;
			}
			set
			{
				if ((this._Submit != value))
				{
					this.OnSubmitChanging(value);
					this.SendPropertyChanging();
					this._Submit = value;
					this.SendPropertyChanged("Submit");
					this.OnSubmitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInput", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateInput
		{
			get
			{
				return this._DateInput;
			}
			set
			{
				if ((this._DateInput != value))
				{
					this.OnDateInputChanging(value);
					this.SendPropertyChanging();
					this._DateInput = value;
					this.SendPropertyChanged("DateInput");
					this.OnDateInputChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DataAutoComplete")]
	public partial class tbl_DataAutoComplete
	{
		
		private long _Id;
		
		private string _DataAutoComplete;
		
		public tbl_DataAutoComplete()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAutoComplete", DbType="NVarChar(400)")]
		public string DataAutoComplete
		{
			get
			{
				return this._DataAutoComplete;
			}
			set
			{
				if ((this._DataAutoComplete != value))
				{
					this._DataAutoComplete = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DEJP")]
	public partial class tbl_DEJP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private string _Truong_01;
		
		private string _Truong_02;
		
		private string _Truong_03;
		
		private string _Truong_04;
		
		private string _Truong_05;
		
		private string _Truong_06;
		
		private string _Truong_07;
		
		private string _Truong_08;
		
		private string _Truong_09;
		
		private string _Truong_10;
		
		private string _Truong_11;
		
		private string _Truong_12;
		
		private string _LoaiPhieu;
		
		private System.Nullable<int> _IdPhieu;
		
		private System.Nullable<int> _Dem;
		
		private System.Nullable<int> _Error;
		
		private System.Nullable<int> _True;
		
		private System.Nullable<System.DateTime> _DateInput;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnTruong_01Changing(string value);
    partial void OnTruong_01Changed();
    partial void OnTruong_02Changing(string value);
    partial void OnTruong_02Changed();
    partial void OnTruong_03Changing(string value);
    partial void OnTruong_03Changed();
    partial void OnTruong_04Changing(string value);
    partial void OnTruong_04Changed();
    partial void OnTruong_05Changing(string value);
    partial void OnTruong_05Changed();
    partial void OnTruong_06Changing(string value);
    partial void OnTruong_06Changed();
    partial void OnTruong_07Changing(string value);
    partial void OnTruong_07Changed();
    partial void OnTruong_08Changing(string value);
    partial void OnTruong_08Changed();
    partial void OnTruong_09Changing(string value);
    partial void OnTruong_09Changed();
    partial void OnTruong_10Changing(string value);
    partial void OnTruong_10Changed();
    partial void OnTruong_11Changing(string value);
    partial void OnTruong_11Changed();
    partial void OnTruong_12Changing(string value);
    partial void OnTruong_12Changed();
    partial void OnLoaiPhieuChanging(string value);
    partial void OnLoaiPhieuChanged();
    partial void OnIdPhieuChanging(System.Nullable<int> value);
    partial void OnIdPhieuChanged();
    partial void OnDemChanging(System.Nullable<int> value);
    partial void OnDemChanged();
    partial void OnErrorChanging(System.Nullable<int> value);
    partial void OnErrorChanged();
    partial void OnTrueChanging(System.Nullable<int> value);
    partial void OnTrueChanged();
    partial void OnDateInputChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInputChanged();
    #endregion
		
		public tbl_DEJP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_01", DbType="NVarChar(255)")]
		public string Truong_01
		{
			get
			{
				return this._Truong_01;
			}
			set
			{
				if ((this._Truong_01 != value))
				{
					this.OnTruong_01Changing(value);
					this.SendPropertyChanging();
					this._Truong_01 = value;
					this.SendPropertyChanged("Truong_01");
					this.OnTruong_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_02", DbType="NVarChar(255)")]
		public string Truong_02
		{
			get
			{
				return this._Truong_02;
			}
			set
			{
				if ((this._Truong_02 != value))
				{
					this.OnTruong_02Changing(value);
					this.SendPropertyChanging();
					this._Truong_02 = value;
					this.SendPropertyChanged("Truong_02");
					this.OnTruong_02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_03", DbType="NVarChar(255)")]
		public string Truong_03
		{
			get
			{
				return this._Truong_03;
			}
			set
			{
				if ((this._Truong_03 != value))
				{
					this.OnTruong_03Changing(value);
					this.SendPropertyChanging();
					this._Truong_03 = value;
					this.SendPropertyChanged("Truong_03");
					this.OnTruong_03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_04", DbType="NVarChar(255)")]
		public string Truong_04
		{
			get
			{
				return this._Truong_04;
			}
			set
			{
				if ((this._Truong_04 != value))
				{
					this.OnTruong_04Changing(value);
					this.SendPropertyChanging();
					this._Truong_04 = value;
					this.SendPropertyChanged("Truong_04");
					this.OnTruong_04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_05", DbType="NVarChar(255)")]
		public string Truong_05
		{
			get
			{
				return this._Truong_05;
			}
			set
			{
				if ((this._Truong_05 != value))
				{
					this.OnTruong_05Changing(value);
					this.SendPropertyChanging();
					this._Truong_05 = value;
					this.SendPropertyChanged("Truong_05");
					this.OnTruong_05Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_06", DbType="NVarChar(255)")]
		public string Truong_06
		{
			get
			{
				return this._Truong_06;
			}
			set
			{
				if ((this._Truong_06 != value))
				{
					this.OnTruong_06Changing(value);
					this.SendPropertyChanging();
					this._Truong_06 = value;
					this.SendPropertyChanged("Truong_06");
					this.OnTruong_06Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_07", DbType="NVarChar(255)")]
		public string Truong_07
		{
			get
			{
				return this._Truong_07;
			}
			set
			{
				if ((this._Truong_07 != value))
				{
					this.OnTruong_07Changing(value);
					this.SendPropertyChanging();
					this._Truong_07 = value;
					this.SendPropertyChanged("Truong_07");
					this.OnTruong_07Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_08", DbType="NVarChar(255)")]
		public string Truong_08
		{
			get
			{
				return this._Truong_08;
			}
			set
			{
				if ((this._Truong_08 != value))
				{
					this.OnTruong_08Changing(value);
					this.SendPropertyChanging();
					this._Truong_08 = value;
					this.SendPropertyChanged("Truong_08");
					this.OnTruong_08Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_09", DbType="NVarChar(255)")]
		public string Truong_09
		{
			get
			{
				return this._Truong_09;
			}
			set
			{
				if ((this._Truong_09 != value))
				{
					this.OnTruong_09Changing(value);
					this.SendPropertyChanging();
					this._Truong_09 = value;
					this.SendPropertyChanged("Truong_09");
					this.OnTruong_09Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_10", DbType="NVarChar(255)")]
		public string Truong_10
		{
			get
			{
				return this._Truong_10;
			}
			set
			{
				if ((this._Truong_10 != value))
				{
					this.OnTruong_10Changing(value);
					this.SendPropertyChanging();
					this._Truong_10 = value;
					this.SendPropertyChanged("Truong_10");
					this.OnTruong_10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_11", DbType="NVarChar(255)")]
		public string Truong_11
		{
			get
			{
				return this._Truong_11;
			}
			set
			{
				if ((this._Truong_11 != value))
				{
					this.OnTruong_11Changing(value);
					this.SendPropertyChanging();
					this._Truong_11 = value;
					this.SendPropertyChanged("Truong_11");
					this.OnTruong_11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_12", DbType="NVarChar(255)")]
		public string Truong_12
		{
			get
			{
				return this._Truong_12;
			}
			set
			{
				if ((this._Truong_12 != value))
				{
					this.OnTruong_12Changing(value);
					this.SendPropertyChanging();
					this._Truong_12 = value;
					this.SendPropertyChanged("Truong_12");
					this.OnTruong_12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiPhieu", DbType="NVarChar(255)")]
		public string LoaiPhieu
		{
			get
			{
				return this._LoaiPhieu;
			}
			set
			{
				if ((this._LoaiPhieu != value))
				{
					this.OnLoaiPhieuChanging(value);
					this.SendPropertyChanging();
					this._LoaiPhieu = value;
					this.SendPropertyChanged("LoaiPhieu");
					this.OnLoaiPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieu", DbType="Int")]
		public System.Nullable<int> IdPhieu
		{
			get
			{
				return this._IdPhieu;
			}
			set
			{
				if ((this._IdPhieu != value))
				{
					this.OnIdPhieuChanging(value);
					this.SendPropertyChanging();
					this._IdPhieu = value;
					this.SendPropertyChanged("IdPhieu");
					this.OnIdPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dem", DbType="Int")]
		public System.Nullable<int> Dem
		{
			get
			{
				return this._Dem;
			}
			set
			{
				if ((this._Dem != value))
				{
					this.OnDemChanging(value);
					this.SendPropertyChanging();
					this._Dem = value;
					this.SendPropertyChanged("Dem");
					this.OnDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Int")]
		public System.Nullable<int> Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_True", DbType="Int")]
		public System.Nullable<int> True
		{
			get
			{
				return this._True;
			}
			set
			{
				if ((this._True != value))
				{
					this.OnTrueChanging(value);
					this.SendPropertyChanging();
					this._True = value;
					this.SendPropertyChanged("True");
					this.OnTrueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInput", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateInput
		{
			get
			{
				return this._DateInput;
			}
			set
			{
				if ((this._DateInput != value))
				{
					this.OnDateInputChanging(value);
					this.SendPropertyChanging();
					this._DateInput = value;
					this.SendPropertyChanged("DateInput");
					this.OnDateInputChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DEJP_Backup")]
	public partial class tbl_DEJP_Backup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private string _Truong_01;
		
		private string _Truong_02;
		
		private string _Truong_03;
		
		private string _Truong_04;
		
		private string _Truong_05;
		
		private string _Truong_06;
		
		private string _Truong_07;
		
		private string _Truong_08;
		
		private string _Truong_09;
		
		private string _Truong_10;
		
		private string _Truong_11;
		
		private string _Truong_12;
		
		private string _LoaiPhieu;
		
		private System.Nullable<int> _IdPhieu;
		
		private System.Nullable<int> _Dem;
		
		private System.Nullable<int> _Error;
		
		private System.Nullable<int> _True;
		
		private System.Nullable<System.DateTime> _DateInput;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnTruong_01Changing(string value);
    partial void OnTruong_01Changed();
    partial void OnTruong_02Changing(string value);
    partial void OnTruong_02Changed();
    partial void OnTruong_03Changing(string value);
    partial void OnTruong_03Changed();
    partial void OnTruong_04Changing(string value);
    partial void OnTruong_04Changed();
    partial void OnTruong_05Changing(string value);
    partial void OnTruong_05Changed();
    partial void OnTruong_06Changing(string value);
    partial void OnTruong_06Changed();
    partial void OnTruong_07Changing(string value);
    partial void OnTruong_07Changed();
    partial void OnTruong_08Changing(string value);
    partial void OnTruong_08Changed();
    partial void OnTruong_09Changing(string value);
    partial void OnTruong_09Changed();
    partial void OnTruong_10Changing(string value);
    partial void OnTruong_10Changed();
    partial void OnTruong_11Changing(string value);
    partial void OnTruong_11Changed();
    partial void OnTruong_12Changing(string value);
    partial void OnTruong_12Changed();
    partial void OnLoaiPhieuChanging(string value);
    partial void OnLoaiPhieuChanged();
    partial void OnIdPhieuChanging(System.Nullable<int> value);
    partial void OnIdPhieuChanged();
    partial void OnDemChanging(System.Nullable<int> value);
    partial void OnDemChanged();
    partial void OnErrorChanging(System.Nullable<int> value);
    partial void OnErrorChanged();
    partial void OnTrueChanging(System.Nullable<int> value);
    partial void OnTrueChanged();
    partial void OnDateInputChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInputChanged();
    #endregion
		
		public tbl_DEJP_Backup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_01", DbType="NVarChar(255)")]
		public string Truong_01
		{
			get
			{
				return this._Truong_01;
			}
			set
			{
				if ((this._Truong_01 != value))
				{
					this.OnTruong_01Changing(value);
					this.SendPropertyChanging();
					this._Truong_01 = value;
					this.SendPropertyChanged("Truong_01");
					this.OnTruong_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_02", DbType="NVarChar(255)")]
		public string Truong_02
		{
			get
			{
				return this._Truong_02;
			}
			set
			{
				if ((this._Truong_02 != value))
				{
					this.OnTruong_02Changing(value);
					this.SendPropertyChanging();
					this._Truong_02 = value;
					this.SendPropertyChanged("Truong_02");
					this.OnTruong_02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_03", DbType="NVarChar(255)")]
		public string Truong_03
		{
			get
			{
				return this._Truong_03;
			}
			set
			{
				if ((this._Truong_03 != value))
				{
					this.OnTruong_03Changing(value);
					this.SendPropertyChanging();
					this._Truong_03 = value;
					this.SendPropertyChanged("Truong_03");
					this.OnTruong_03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_04", DbType="NVarChar(255)")]
		public string Truong_04
		{
			get
			{
				return this._Truong_04;
			}
			set
			{
				if ((this._Truong_04 != value))
				{
					this.OnTruong_04Changing(value);
					this.SendPropertyChanging();
					this._Truong_04 = value;
					this.SendPropertyChanged("Truong_04");
					this.OnTruong_04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_05", DbType="NVarChar(255)")]
		public string Truong_05
		{
			get
			{
				return this._Truong_05;
			}
			set
			{
				if ((this._Truong_05 != value))
				{
					this.OnTruong_05Changing(value);
					this.SendPropertyChanging();
					this._Truong_05 = value;
					this.SendPropertyChanged("Truong_05");
					this.OnTruong_05Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_06", DbType="NVarChar(255)")]
		public string Truong_06
		{
			get
			{
				return this._Truong_06;
			}
			set
			{
				if ((this._Truong_06 != value))
				{
					this.OnTruong_06Changing(value);
					this.SendPropertyChanging();
					this._Truong_06 = value;
					this.SendPropertyChanged("Truong_06");
					this.OnTruong_06Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_07", DbType="NVarChar(255)")]
		public string Truong_07
		{
			get
			{
				return this._Truong_07;
			}
			set
			{
				if ((this._Truong_07 != value))
				{
					this.OnTruong_07Changing(value);
					this.SendPropertyChanging();
					this._Truong_07 = value;
					this.SendPropertyChanged("Truong_07");
					this.OnTruong_07Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_08", DbType="NVarChar(255)")]
		public string Truong_08
		{
			get
			{
				return this._Truong_08;
			}
			set
			{
				if ((this._Truong_08 != value))
				{
					this.OnTruong_08Changing(value);
					this.SendPropertyChanging();
					this._Truong_08 = value;
					this.SendPropertyChanged("Truong_08");
					this.OnTruong_08Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_09", DbType="NVarChar(255)")]
		public string Truong_09
		{
			get
			{
				return this._Truong_09;
			}
			set
			{
				if ((this._Truong_09 != value))
				{
					this.OnTruong_09Changing(value);
					this.SendPropertyChanging();
					this._Truong_09 = value;
					this.SendPropertyChanged("Truong_09");
					this.OnTruong_09Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_10", DbType="NVarChar(255)")]
		public string Truong_10
		{
			get
			{
				return this._Truong_10;
			}
			set
			{
				if ((this._Truong_10 != value))
				{
					this.OnTruong_10Changing(value);
					this.SendPropertyChanging();
					this._Truong_10 = value;
					this.SendPropertyChanged("Truong_10");
					this.OnTruong_10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_11", DbType="NVarChar(255)")]
		public string Truong_11
		{
			get
			{
				return this._Truong_11;
			}
			set
			{
				if ((this._Truong_11 != value))
				{
					this.OnTruong_11Changing(value);
					this.SendPropertyChanging();
					this._Truong_11 = value;
					this.SendPropertyChanged("Truong_11");
					this.OnTruong_11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_12", DbType="NVarChar(255)")]
		public string Truong_12
		{
			get
			{
				return this._Truong_12;
			}
			set
			{
				if ((this._Truong_12 != value))
				{
					this.OnTruong_12Changing(value);
					this.SendPropertyChanging();
					this._Truong_12 = value;
					this.SendPropertyChanged("Truong_12");
					this.OnTruong_12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiPhieu", DbType="NVarChar(255)")]
		public string LoaiPhieu
		{
			get
			{
				return this._LoaiPhieu;
			}
			set
			{
				if ((this._LoaiPhieu != value))
				{
					this.OnLoaiPhieuChanging(value);
					this.SendPropertyChanging();
					this._LoaiPhieu = value;
					this.SendPropertyChanged("LoaiPhieu");
					this.OnLoaiPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieu", DbType="Int")]
		public System.Nullable<int> IdPhieu
		{
			get
			{
				return this._IdPhieu;
			}
			set
			{
				if ((this._IdPhieu != value))
				{
					this.OnIdPhieuChanging(value);
					this.SendPropertyChanging();
					this._IdPhieu = value;
					this.SendPropertyChanged("IdPhieu");
					this.OnIdPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dem", DbType="Int")]
		public System.Nullable<int> Dem
		{
			get
			{
				return this._Dem;
			}
			set
			{
				if ((this._Dem != value))
				{
					this.OnDemChanging(value);
					this.SendPropertyChanging();
					this._Dem = value;
					this.SendPropertyChanged("Dem");
					this.OnDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Int")]
		public System.Nullable<int> Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_True", DbType="Int")]
		public System.Nullable<int> True
		{
			get
			{
				return this._True;
			}
			set
			{
				if ((this._True != value))
				{
					this.OnTrueChanging(value);
					this.SendPropertyChanging();
					this._True = value;
					this.SendPropertyChanged("True");
					this.OnTrueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInput", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateInput
		{
			get
			{
				return this._DateInput;
			}
			set
			{
				if ((this._DateInput != value))
				{
					this.OnDateInputChanging(value);
					this.SendPropertyChanging();
					this._DateInput = value;
					this.SendPropertyChanged("DateInput");
					this.OnDateInputChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DESO")]
	public partial class tbl_DESO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private string _Truong_01;
		
		private string _Truong_02;
		
		private string _Truong_03;
		
		private string _Truong_04;
		
		private string _Truong_05;
		
		private string _Truong_06;
		
		private string _Truong_07;
		
		private string _Truong_08;
		
		private string _Truong_09;
		
		private string _Truong_10;
		
		private string _Truong_11;
		
		private string _Truong_12;
		
		private string _LoaiPhieu;
		
		private System.Nullable<int> _IdPhieu;
		
		private System.Nullable<int> _Dem;
		
		private System.Nullable<int> _Error;
		
		private System.Nullable<int> _True;
		
		private System.Nullable<System.DateTime> _DateInput;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnTruong_01Changing(string value);
    partial void OnTruong_01Changed();
    partial void OnTruong_02Changing(string value);
    partial void OnTruong_02Changed();
    partial void OnTruong_03Changing(string value);
    partial void OnTruong_03Changed();
    partial void OnTruong_04Changing(string value);
    partial void OnTruong_04Changed();
    partial void OnTruong_05Changing(string value);
    partial void OnTruong_05Changed();
    partial void OnTruong_06Changing(string value);
    partial void OnTruong_06Changed();
    partial void OnTruong_07Changing(string value);
    partial void OnTruong_07Changed();
    partial void OnTruong_08Changing(string value);
    partial void OnTruong_08Changed();
    partial void OnTruong_09Changing(string value);
    partial void OnTruong_09Changed();
    partial void OnTruong_10Changing(string value);
    partial void OnTruong_10Changed();
    partial void OnTruong_11Changing(string value);
    partial void OnTruong_11Changed();
    partial void OnTruong_12Changing(string value);
    partial void OnTruong_12Changed();
    partial void OnLoaiPhieuChanging(string value);
    partial void OnLoaiPhieuChanged();
    partial void OnIdPhieuChanging(System.Nullable<int> value);
    partial void OnIdPhieuChanged();
    partial void OnDemChanging(System.Nullable<int> value);
    partial void OnDemChanged();
    partial void OnErrorChanging(System.Nullable<int> value);
    partial void OnErrorChanged();
    partial void OnTrueChanging(System.Nullable<int> value);
    partial void OnTrueChanged();
    partial void OnDateInputChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInputChanged();
    #endregion
		
		public tbl_DESO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_01", DbType="NVarChar(255)")]
		public string Truong_01
		{
			get
			{
				return this._Truong_01;
			}
			set
			{
				if ((this._Truong_01 != value))
				{
					this.OnTruong_01Changing(value);
					this.SendPropertyChanging();
					this._Truong_01 = value;
					this.SendPropertyChanged("Truong_01");
					this.OnTruong_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_02", DbType="NVarChar(255)")]
		public string Truong_02
		{
			get
			{
				return this._Truong_02;
			}
			set
			{
				if ((this._Truong_02 != value))
				{
					this.OnTruong_02Changing(value);
					this.SendPropertyChanging();
					this._Truong_02 = value;
					this.SendPropertyChanged("Truong_02");
					this.OnTruong_02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_03", DbType="NVarChar(255)")]
		public string Truong_03
		{
			get
			{
				return this._Truong_03;
			}
			set
			{
				if ((this._Truong_03 != value))
				{
					this.OnTruong_03Changing(value);
					this.SendPropertyChanging();
					this._Truong_03 = value;
					this.SendPropertyChanged("Truong_03");
					this.OnTruong_03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_04", DbType="NVarChar(255)")]
		public string Truong_04
		{
			get
			{
				return this._Truong_04;
			}
			set
			{
				if ((this._Truong_04 != value))
				{
					this.OnTruong_04Changing(value);
					this.SendPropertyChanging();
					this._Truong_04 = value;
					this.SendPropertyChanged("Truong_04");
					this.OnTruong_04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_05", DbType="NVarChar(255)")]
		public string Truong_05
		{
			get
			{
				return this._Truong_05;
			}
			set
			{
				if ((this._Truong_05 != value))
				{
					this.OnTruong_05Changing(value);
					this.SendPropertyChanging();
					this._Truong_05 = value;
					this.SendPropertyChanged("Truong_05");
					this.OnTruong_05Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_06", DbType="NVarChar(255)")]
		public string Truong_06
		{
			get
			{
				return this._Truong_06;
			}
			set
			{
				if ((this._Truong_06 != value))
				{
					this.OnTruong_06Changing(value);
					this.SendPropertyChanging();
					this._Truong_06 = value;
					this.SendPropertyChanged("Truong_06");
					this.OnTruong_06Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_07", DbType="NVarChar(255)")]
		public string Truong_07
		{
			get
			{
				return this._Truong_07;
			}
			set
			{
				if ((this._Truong_07 != value))
				{
					this.OnTruong_07Changing(value);
					this.SendPropertyChanging();
					this._Truong_07 = value;
					this.SendPropertyChanged("Truong_07");
					this.OnTruong_07Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_08", DbType="NVarChar(255)")]
		public string Truong_08
		{
			get
			{
				return this._Truong_08;
			}
			set
			{
				if ((this._Truong_08 != value))
				{
					this.OnTruong_08Changing(value);
					this.SendPropertyChanging();
					this._Truong_08 = value;
					this.SendPropertyChanged("Truong_08");
					this.OnTruong_08Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_09", DbType="NVarChar(255)")]
		public string Truong_09
		{
			get
			{
				return this._Truong_09;
			}
			set
			{
				if ((this._Truong_09 != value))
				{
					this.OnTruong_09Changing(value);
					this.SendPropertyChanging();
					this._Truong_09 = value;
					this.SendPropertyChanged("Truong_09");
					this.OnTruong_09Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_10", DbType="NVarChar(255)")]
		public string Truong_10
		{
			get
			{
				return this._Truong_10;
			}
			set
			{
				if ((this._Truong_10 != value))
				{
					this.OnTruong_10Changing(value);
					this.SendPropertyChanging();
					this._Truong_10 = value;
					this.SendPropertyChanged("Truong_10");
					this.OnTruong_10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_11", DbType="NVarChar(255)")]
		public string Truong_11
		{
			get
			{
				return this._Truong_11;
			}
			set
			{
				if ((this._Truong_11 != value))
				{
					this.OnTruong_11Changing(value);
					this.SendPropertyChanging();
					this._Truong_11 = value;
					this.SendPropertyChanged("Truong_11");
					this.OnTruong_11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_12", DbType="NVarChar(255)")]
		public string Truong_12
		{
			get
			{
				return this._Truong_12;
			}
			set
			{
				if ((this._Truong_12 != value))
				{
					this.OnTruong_12Changing(value);
					this.SendPropertyChanging();
					this._Truong_12 = value;
					this.SendPropertyChanged("Truong_12");
					this.OnTruong_12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiPhieu", DbType="NVarChar(255)")]
		public string LoaiPhieu
		{
			get
			{
				return this._LoaiPhieu;
			}
			set
			{
				if ((this._LoaiPhieu != value))
				{
					this.OnLoaiPhieuChanging(value);
					this.SendPropertyChanging();
					this._LoaiPhieu = value;
					this.SendPropertyChanged("LoaiPhieu");
					this.OnLoaiPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieu", DbType="Int")]
		public System.Nullable<int> IdPhieu
		{
			get
			{
				return this._IdPhieu;
			}
			set
			{
				if ((this._IdPhieu != value))
				{
					this.OnIdPhieuChanging(value);
					this.SendPropertyChanging();
					this._IdPhieu = value;
					this.SendPropertyChanged("IdPhieu");
					this.OnIdPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dem", DbType="Int")]
		public System.Nullable<int> Dem
		{
			get
			{
				return this._Dem;
			}
			set
			{
				if ((this._Dem != value))
				{
					this.OnDemChanging(value);
					this.SendPropertyChanging();
					this._Dem = value;
					this.SendPropertyChanged("Dem");
					this.OnDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Int")]
		public System.Nullable<int> Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_True", DbType="Int")]
		public System.Nullable<int> True
		{
			get
			{
				return this._True;
			}
			set
			{
				if ((this._True != value))
				{
					this.OnTrueChanging(value);
					this.SendPropertyChanging();
					this._True = value;
					this.SendPropertyChanged("True");
					this.OnTrueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInput", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateInput
		{
			get
			{
				return this._DateInput;
			}
			set
			{
				if ((this._DateInput != value))
				{
					this.OnDateInputChanging(value);
					this.SendPropertyChanging();
					this._DateInput = value;
					this.SendPropertyChanged("DateInput");
					this.OnDateInputChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DESO_Backup")]
	public partial class tbl_DESO_Backup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private string _Truong_01;
		
		private string _Truong_02;
		
		private string _Truong_03;
		
		private string _Truong_04;
		
		private string _Truong_05;
		
		private string _Truong_06;
		
		private string _Truong_07;
		
		private string _Truong_08;
		
		private string _Truong_09;
		
		private string _Truong_10;
		
		private string _Truong_11;
		
		private string _Truong_12;
		
		private string _LoaiPhieu;
		
		private System.Nullable<int> _IdPhieu;
		
		private System.Nullable<int> _Dem;
		
		private System.Nullable<int> _Error;
		
		private System.Nullable<int> _True;
		
		private System.Nullable<System.DateTime> _DateInput;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnTruong_01Changing(string value);
    partial void OnTruong_01Changed();
    partial void OnTruong_02Changing(string value);
    partial void OnTruong_02Changed();
    partial void OnTruong_03Changing(string value);
    partial void OnTruong_03Changed();
    partial void OnTruong_04Changing(string value);
    partial void OnTruong_04Changed();
    partial void OnTruong_05Changing(string value);
    partial void OnTruong_05Changed();
    partial void OnTruong_06Changing(string value);
    partial void OnTruong_06Changed();
    partial void OnTruong_07Changing(string value);
    partial void OnTruong_07Changed();
    partial void OnTruong_08Changing(string value);
    partial void OnTruong_08Changed();
    partial void OnTruong_09Changing(string value);
    partial void OnTruong_09Changed();
    partial void OnTruong_10Changing(string value);
    partial void OnTruong_10Changed();
    partial void OnTruong_11Changing(string value);
    partial void OnTruong_11Changed();
    partial void OnTruong_12Changing(string value);
    partial void OnTruong_12Changed();
    partial void OnLoaiPhieuChanging(string value);
    partial void OnLoaiPhieuChanged();
    partial void OnIdPhieuChanging(System.Nullable<int> value);
    partial void OnIdPhieuChanged();
    partial void OnDemChanging(System.Nullable<int> value);
    partial void OnDemChanged();
    partial void OnErrorChanging(System.Nullable<int> value);
    partial void OnErrorChanged();
    partial void OnTrueChanging(System.Nullable<int> value);
    partial void OnTrueChanged();
    partial void OnDateInputChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInputChanged();
    #endregion
		
		public tbl_DESO_Backup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_01", DbType="NVarChar(255)")]
		public string Truong_01
		{
			get
			{
				return this._Truong_01;
			}
			set
			{
				if ((this._Truong_01 != value))
				{
					this.OnTruong_01Changing(value);
					this.SendPropertyChanging();
					this._Truong_01 = value;
					this.SendPropertyChanged("Truong_01");
					this.OnTruong_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_02", DbType="NVarChar(255)")]
		public string Truong_02
		{
			get
			{
				return this._Truong_02;
			}
			set
			{
				if ((this._Truong_02 != value))
				{
					this.OnTruong_02Changing(value);
					this.SendPropertyChanging();
					this._Truong_02 = value;
					this.SendPropertyChanged("Truong_02");
					this.OnTruong_02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_03", DbType="NVarChar(255)")]
		public string Truong_03
		{
			get
			{
				return this._Truong_03;
			}
			set
			{
				if ((this._Truong_03 != value))
				{
					this.OnTruong_03Changing(value);
					this.SendPropertyChanging();
					this._Truong_03 = value;
					this.SendPropertyChanged("Truong_03");
					this.OnTruong_03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_04", DbType="NVarChar(255)")]
		public string Truong_04
		{
			get
			{
				return this._Truong_04;
			}
			set
			{
				if ((this._Truong_04 != value))
				{
					this.OnTruong_04Changing(value);
					this.SendPropertyChanging();
					this._Truong_04 = value;
					this.SendPropertyChanged("Truong_04");
					this.OnTruong_04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_05", DbType="NVarChar(255)")]
		public string Truong_05
		{
			get
			{
				return this._Truong_05;
			}
			set
			{
				if ((this._Truong_05 != value))
				{
					this.OnTruong_05Changing(value);
					this.SendPropertyChanging();
					this._Truong_05 = value;
					this.SendPropertyChanged("Truong_05");
					this.OnTruong_05Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_06", DbType="NVarChar(255)")]
		public string Truong_06
		{
			get
			{
				return this._Truong_06;
			}
			set
			{
				if ((this._Truong_06 != value))
				{
					this.OnTruong_06Changing(value);
					this.SendPropertyChanging();
					this._Truong_06 = value;
					this.SendPropertyChanged("Truong_06");
					this.OnTruong_06Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_07", DbType="NVarChar(255)")]
		public string Truong_07
		{
			get
			{
				return this._Truong_07;
			}
			set
			{
				if ((this._Truong_07 != value))
				{
					this.OnTruong_07Changing(value);
					this.SendPropertyChanging();
					this._Truong_07 = value;
					this.SendPropertyChanged("Truong_07");
					this.OnTruong_07Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_08", DbType="NVarChar(255)")]
		public string Truong_08
		{
			get
			{
				return this._Truong_08;
			}
			set
			{
				if ((this._Truong_08 != value))
				{
					this.OnTruong_08Changing(value);
					this.SendPropertyChanging();
					this._Truong_08 = value;
					this.SendPropertyChanged("Truong_08");
					this.OnTruong_08Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_09", DbType="NVarChar(255)")]
		public string Truong_09
		{
			get
			{
				return this._Truong_09;
			}
			set
			{
				if ((this._Truong_09 != value))
				{
					this.OnTruong_09Changing(value);
					this.SendPropertyChanging();
					this._Truong_09 = value;
					this.SendPropertyChanged("Truong_09");
					this.OnTruong_09Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_10", DbType="NVarChar(255)")]
		public string Truong_10
		{
			get
			{
				return this._Truong_10;
			}
			set
			{
				if ((this._Truong_10 != value))
				{
					this.OnTruong_10Changing(value);
					this.SendPropertyChanging();
					this._Truong_10 = value;
					this.SendPropertyChanged("Truong_10");
					this.OnTruong_10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_11", DbType="NVarChar(255)")]
		public string Truong_11
		{
			get
			{
				return this._Truong_11;
			}
			set
			{
				if ((this._Truong_11 != value))
				{
					this.OnTruong_11Changing(value);
					this.SendPropertyChanging();
					this._Truong_11 = value;
					this.SendPropertyChanged("Truong_11");
					this.OnTruong_11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_12", DbType="NVarChar(255)")]
		public string Truong_12
		{
			get
			{
				return this._Truong_12;
			}
			set
			{
				if ((this._Truong_12 != value))
				{
					this.OnTruong_12Changing(value);
					this.SendPropertyChanging();
					this._Truong_12 = value;
					this.SendPropertyChanged("Truong_12");
					this.OnTruong_12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiPhieu", DbType="NVarChar(255)")]
		public string LoaiPhieu
		{
			get
			{
				return this._LoaiPhieu;
			}
			set
			{
				if ((this._LoaiPhieu != value))
				{
					this.OnLoaiPhieuChanging(value);
					this.SendPropertyChanging();
					this._LoaiPhieu = value;
					this.SendPropertyChanged("LoaiPhieu");
					this.OnLoaiPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieu", DbType="Int")]
		public System.Nullable<int> IdPhieu
		{
			get
			{
				return this._IdPhieu;
			}
			set
			{
				if ((this._IdPhieu != value))
				{
					this.OnIdPhieuChanging(value);
					this.SendPropertyChanging();
					this._IdPhieu = value;
					this.SendPropertyChanged("IdPhieu");
					this.OnIdPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dem", DbType="Int")]
		public System.Nullable<int> Dem
		{
			get
			{
				return this._Dem;
			}
			set
			{
				if ((this._Dem != value))
				{
					this.OnDemChanging(value);
					this.SendPropertyChanging();
					this._Dem = value;
					this.SendPropertyChanged("Dem");
					this.OnDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Int")]
		public System.Nullable<int> Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_True", DbType="Int")]
		public System.Nullable<int> True
		{
			get
			{
				return this._True;
			}
			set
			{
				if ((this._True != value))
				{
					this.OnTrueChanging(value);
					this.SendPropertyChanging();
					this._True = value;
					this.SendPropertyChanged("True");
					this.OnTrueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInput", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateInput
		{
			get
			{
				return this._DateInput;
			}
			set
			{
				if ((this._DateInput != value))
				{
					this.OnDateInputChanging(value);
					this.SendPropertyChanging();
					this._DateInput = value;
					this.SendPropertyChanged("DateInput");
					this.OnDateInputChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Image")]
	public partial class tbl_Image : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _idimage;
		
		private string _fbatchname;
		
		private string _UserNameDESo;
		
		private int _ReadImageDESo;
		
		private string _UserNameDEJP;
		
		private int _ReadImageDEJP;
		
		private System.Nullable<int> _CheckedDESo;
		
		private System.Nullable<int> _CheckedDEJP;
		
		private string _TienDoDESO;
		
		private string _TienDoDEJP;
		
		private string _NienHieu;
		
		private string _Page;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnidimageChanging(string value);
    partial void OnidimageChanged();
    partial void OnfbatchnameChanging(string value);
    partial void OnfbatchnameChanged();
    partial void OnUserNameDESoChanging(string value);
    partial void OnUserNameDESoChanged();
    partial void OnReadImageDESoChanging(int value);
    partial void OnReadImageDESoChanged();
    partial void OnUserNameDEJPChanging(string value);
    partial void OnUserNameDEJPChanged();
    partial void OnReadImageDEJPChanging(int value);
    partial void OnReadImageDEJPChanged();
    partial void OnCheckedDESoChanging(System.Nullable<int> value);
    partial void OnCheckedDESoChanged();
    partial void OnCheckedDEJPChanging(System.Nullable<int> value);
    partial void OnCheckedDEJPChanged();
    partial void OnTienDoDESOChanging(string value);
    partial void OnTienDoDESOChanged();
    partial void OnTienDoDEJPChanging(string value);
    partial void OnTienDoDEJPChanged();
    partial void OnNienHieuChanging(string value);
    partial void OnNienHieuChanged();
    partial void OnPageChanging(string value);
    partial void OnPageChanged();
    #endregion
		
		public tbl_Image()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL")]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idimage", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idimage
		{
			get
			{
				return this._idimage;
			}
			set
			{
				if ((this._idimage != value))
				{
					this.OnidimageChanging(value);
					this.SendPropertyChanging();
					this._idimage = value;
					this.SendPropertyChanged("idimage");
					this.OnidimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fbatchname", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fbatchname
		{
			get
			{
				return this._fbatchname;
			}
			set
			{
				if ((this._fbatchname != value))
				{
					this.OnfbatchnameChanging(value);
					this.SendPropertyChanging();
					this._fbatchname = value;
					this.SendPropertyChanged("fbatchname");
					this.OnfbatchnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNameDESo", DbType="NVarChar(200)")]
		public string UserNameDESo
		{
			get
			{
				return this._UserNameDESo;
			}
			set
			{
				if ((this._UserNameDESo != value))
				{
					this.OnUserNameDESoChanging(value);
					this.SendPropertyChanging();
					this._UserNameDESo = value;
					this.SendPropertyChanged("UserNameDESo");
					this.OnUserNameDESoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadImageDESo", DbType="Int NOT NULL")]
		public int ReadImageDESo
		{
			get
			{
				return this._ReadImageDESo;
			}
			set
			{
				if ((this._ReadImageDESo != value))
				{
					this.OnReadImageDESoChanging(value);
					this.SendPropertyChanging();
					this._ReadImageDESo = value;
					this.SendPropertyChanged("ReadImageDESo");
					this.OnReadImageDESoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNameDEJP", DbType="NVarChar(200)")]
		public string UserNameDEJP
		{
			get
			{
				return this._UserNameDEJP;
			}
			set
			{
				if ((this._UserNameDEJP != value))
				{
					this.OnUserNameDEJPChanging(value);
					this.SendPropertyChanging();
					this._UserNameDEJP = value;
					this.SendPropertyChanged("UserNameDEJP");
					this.OnUserNameDEJPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadImageDEJP", DbType="Int NOT NULL")]
		public int ReadImageDEJP
		{
			get
			{
				return this._ReadImageDEJP;
			}
			set
			{
				if ((this._ReadImageDEJP != value))
				{
					this.OnReadImageDEJPChanging(value);
					this.SendPropertyChanging();
					this._ReadImageDEJP = value;
					this.SendPropertyChanged("ReadImageDEJP");
					this.OnReadImageDEJPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckedDESo", DbType="Int")]
		public System.Nullable<int> CheckedDESo
		{
			get
			{
				return this._CheckedDESo;
			}
			set
			{
				if ((this._CheckedDESo != value))
				{
					this.OnCheckedDESoChanging(value);
					this.SendPropertyChanging();
					this._CheckedDESo = value;
					this.SendPropertyChanged("CheckedDESo");
					this.OnCheckedDESoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckedDEJP", DbType="Int")]
		public System.Nullable<int> CheckedDEJP
		{
			get
			{
				return this._CheckedDEJP;
			}
			set
			{
				if ((this._CheckedDEJP != value))
				{
					this.OnCheckedDEJPChanging(value);
					this.SendPropertyChanging();
					this._CheckedDEJP = value;
					this.SendPropertyChanged("CheckedDEJP");
					this.OnCheckedDEJPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienDoDESO", DbType="NVarChar(100)")]
		public string TienDoDESO
		{
			get
			{
				return this._TienDoDESO;
			}
			set
			{
				if ((this._TienDoDESO != value))
				{
					this.OnTienDoDESOChanging(value);
					this.SendPropertyChanging();
					this._TienDoDESO = value;
					this.SendPropertyChanged("TienDoDESO");
					this.OnTienDoDESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienDoDEJP", DbType="NVarChar(100)")]
		public string TienDoDEJP
		{
			get
			{
				return this._TienDoDEJP;
			}
			set
			{
				if ((this._TienDoDEJP != value))
				{
					this.OnTienDoDEJPChanging(value);
					this.SendPropertyChanging();
					this._TienDoDEJP = value;
					this.SendPropertyChanged("TienDoDEJP");
					this.OnTienDoDEJPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NienHieu", DbType="NVarChar(255)")]
		public string NienHieu
		{
			get
			{
				return this._NienHieu;
			}
			set
			{
				if ((this._NienHieu != value))
				{
					this.OnNienHieuChanging(value);
					this.SendPropertyChanging();
					this._NienHieu = value;
					this.SendPropertyChanged("NienHieu");
					this.OnNienHieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Page", DbType="NVarChar(255)")]
		public string Page
		{
			get
			{
				return this._Page;
			}
			set
			{
				if ((this._Page != value))
				{
					this.OnPageChanging(value);
					this.SendPropertyChanging();
					this._Page = value;
					this.SendPropertyChanged("Page");
					this.OnPageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_LogFile")]
	public partial class tbl_LogFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Username;
		
		private string _Info;
		
		private System.Nullable<System.DateTime> _DateLog;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnInfoChanging(string value);
    partial void OnInfoChanged();
    partial void OnDateLogChanging(System.Nullable<System.DateTime> value);
    partial void OnDateLogChanged();
    #endregion
		
		public tbl_LogFile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(200)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Info", DbType="NVarChar(2000)")]
		public string Info
		{
			get
			{
				return this._Info;
			}
			set
			{
				if ((this._Info != value))
				{
					this.OnInfoChanging(value);
					this.SendPropertyChanging();
					this._Info = value;
					this.SendPropertyChanged("Info");
					this.OnInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLog", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateLog
		{
			get
			{
				return this._DateLog;
			}
			set
			{
				if ((this._DateLog != value))
				{
					this.OnDateLogChanging(value);
					this.SendPropertyChanging();
					this._DateLog = value;
					this.SendPropertyChanged("DateLog");
					this.OnDateLogChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_MissCheck_DEJP")]
	public partial class tbl_MissCheck_DEJP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private System.Nullable<int> _Submit;
		
		private System.Nullable<System.DateTime> _DateCheck;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnSubmitChanging(System.Nullable<int> value);
    partial void OnSubmitChanged();
    partial void OnDateCheckChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCheckChanged();
    #endregion
		
		public tbl_MissCheck_DEJP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(255)")]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(255)")]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Submit", DbType="Int")]
		public System.Nullable<int> Submit
		{
			get
			{
				return this._Submit;
			}
			set
			{
				if ((this._Submit != value))
				{
					this.OnSubmitChanging(value);
					this.SendPropertyChanging();
					this._Submit = value;
					this.SendPropertyChanged("Submit");
					this.OnSubmitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCheck", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCheck
		{
			get
			{
				return this._DateCheck;
			}
			set
			{
				if ((this._DateCheck != value))
				{
					this.OnDateCheckChanging(value);
					this.SendPropertyChanging();
					this._DateCheck = value;
					this.SendPropertyChanged("DateCheck");
					this.OnDateCheckChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_MissCheck_DESO")]
	public partial class tbl_MissCheck_DESO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private System.Nullable<int> _Submit;
		
		private System.Nullable<System.DateTime> _DateCheck;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnSubmitChanging(System.Nullable<int> value);
    partial void OnSubmitChanged();
    partial void OnDateCheckChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCheckChanged();
    #endregion
		
		public tbl_MissCheck_DESO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(255)")]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(255)")]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Submit", DbType="Int")]
		public System.Nullable<int> Submit
		{
			get
			{
				return this._Submit;
			}
			set
			{
				if ((this._Submit != value))
				{
					this.OnSubmitChanging(value);
					this.SendPropertyChanging();
					this._Submit = value;
					this.SendPropertyChanged("Submit");
					this.OnSubmitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCheck", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCheck
		{
			get
			{
				return this._DateCheck;
			}
			set
			{
				if ((this._DateCheck != value))
				{
					this.OnDateCheckChanging(value);
					this.SendPropertyChanging();
					this._DateCheck = value;
					this.SendPropertyChanged("DateCheck");
					this.OnDateCheckChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_MissImage_DEJP")]
	public partial class tbl_MissImage_DEJP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private System.Nullable<int> _Submit;
		
		private System.Nullable<System.DateTime> _DateInput;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnSubmitChanging(System.Nullable<int> value);
    partial void OnSubmitChanged();
    partial void OnDateInputChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInputChanged();
    #endregion
		
		public tbl_MissImage_DEJP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Submit", DbType="Int")]
		public System.Nullable<int> Submit
		{
			get
			{
				return this._Submit;
			}
			set
			{
				if ((this._Submit != value))
				{
					this.OnSubmitChanging(value);
					this.SendPropertyChanging();
					this._Submit = value;
					this.SendPropertyChanged("Submit");
					this.OnSubmitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInput", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateInput
		{
			get
			{
				return this._DateInput;
			}
			set
			{
				if ((this._DateInput != value))
				{
					this.OnDateInputChanging(value);
					this.SendPropertyChanging();
					this._DateInput = value;
					this.SendPropertyChanged("DateInput");
					this.OnDateInputChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class LayHinhMoi_DeJPResult
	{
		
		private string _Column1;
		
		public LayHinhMoi_DeJPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="NVarChar(255)")]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
